SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT * p.PRICE) as TOTAL_SALES
FROM FOOD_ORDER o
LEFT JOIN FOOD_PRODUCT p
ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY p.PRODUCT_ID
ORDER  BY TOTAL_SALES desc, p.PRODUCT_ID asc